version: "2"
networks:

  default:
    driver: bridge
    
services:
  tomcat:
    image: tobecrazy/ubuntu-young:latest
    container_name: tomcat
    ports:
     - "8081:8080"
    networks:
     - default
    volumes:
     - ./export/ROOT:/usr/local/tomcat/webapps/ROOT
     - ./export/conf:/usr/local/tomcat/conf
    mem_limit: 2G
