version: "2"
networks:

  default:
    driver: bridge
    
services:
  tomcat:
    image: tobecrazy/ubuntu-young:latest
    container_name: tomcat
    ports:
     - "8081:8080"
    networks:
     - default
    volumes:
     - ./export/ROOT:/opt/tomcat8/webapps/ROOT
    mem_limit: 2G
